services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - bugraaydingoz-web
      - myanaesthesie-web
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  bugraaydingoz-web:
    build:
      context: ..
      dockerfile: infra/bugraaydingoz-web.Dockerfile
    restart: unless-stopped
    expose:
      - "3000"

  myanaesthesie-web:
    build:
      context: ..
      dockerfile: infra/myanaesthesie-web.Dockerfile
    restart: unless-stopped
    expose:
      - "3000"

volumes:
  caddy_data:
  caddy_config:
